# Site settings
title: Jay Liu
email: soon.nerd@gmail.com
url: http://p-mob2015.github.io
description: React - Node - RoR
meta_author: Jay Liu

about:
  header: About
  content:
      left: I strive to become a <a href="http://blog.codinghorror.com/a-pragmatic-quick-reference/" target="_new">Pragmatic Programmer</a>. I put special emphasis on software architecture. TDD, SOLID principles and Design patterns are the paradigms I live by as a programmer. I seek the responsibility, whether it is leading a team or owning a feature of the project.
      right: In my free time, I enjoy planting, cooking and writing. I am also a Karate green belt. Practicing strong self-discipline is what makes my life vigorous. As a bookworm and a coffee mania, a good book and an original coffee mug are the best presents for me.
      bottom: I live in Mexico City, Mexico
  interests:
    header: Interests as of Late
    content:
      left:
        header: Now
        list:
          - item: Django
          - item: SOLID Principles
          - item: Open-source
      center:
        header: Soon
        list:
          - item: Visual Studio Mastery
          - item: IOT
          - item: Blockchain
      right:
        header: Later
        list:
          - item: ThreeJS
          - item: Swift
          - item: Machine Learning
  button:
    text: Download My Resume
    href: /resume/jay-liu-resume-2019-07.pdf

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname: https://help.disqus.com/customer/portal/articles/466208
disqus_shortname:

# If you have Google Analytics account setup, enter your tracker ID, eg. A-12312312-1
google_analytics_tracker_id:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 101010 #80B3FF
  primary-rgb: "255,0,0" #"128,179,255"
  secondary-light: 58635a #FD6E8A
  secondary: 38433a #FD6E8A
  secondary-dark: 18231a #A2122F
  blog-text: 222
  link: 1a77bd

# Blog settings
blog:
  labels:
    modal-close: Close

# Markdown/syntax highlighter settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

# Portfolio settings
portfolio:
  labels:
    team: Team
    project-date: Date
    application: Application
    tech: Technologies
    concepts: Concepts
    tools: Tools
    stack: Stack
    modal-close: Close

# Footer settings
footer:
  location-header: Location
  location: Mexico City, Mexico
  copyright: Jay Liu. All Rights Reserved.
  social: My Other Whereabouts
  new-thoughts: New Thoughts

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc. search them in main.css)
social:
  - title: github
    tooltip: "Github: Code I am writing"
    url: https://github.com/p-mob2015
  - title: linkedin
    tooltip: "Linkedin: Places I've worked"
    url: https://www.linkedin.com/in/jay-liu-dev
  - title: goodreads
    tooltip: "Goodreads: Books I've been reading"
    url: http://www.goodreads.com/jsliu

# Build settings
permalink: pretty
